# Base configs
baseurl: "https://liaturchi.github.io/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Lia Turchi"
subtitle: "Works by art student Lia Turchi"
author: "Lia Turchi"
header:
 title: "Photography"
 subtitle: "by Lia Turchi"
footer:
 name: "Hi, my name is Lia"
 bio: "I am a student at the Brera Academy of Fine Arts. I'm currently attending the school o fNew Technology in Arts."
      "I'm based in Como, Lombardy, Italy"
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/rampatra/photography\">fork this repo on github</a> ;)"
# web_design: "AJ"

social_urls:
  instagram: "https://www.instagram.com/toiminot"
  github: "https://github.com/liaturchi"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
